services:
  _defaults:
    autowire: true
    autoconfigure: true
  Alnv\ContaoGroundingPagesBundle\Pages\GroundingPageController:
    tags: [ contao.page ]
  Alnv\ContaoGroundingPagesBundle\EventListener\GetPageLayoutListener:
    tags:
      - { name: contao.hook, hook: getPageLayout }
  Alnv\ContaoGroundingPagesBundle\EventListener\GeneratePageListener:
    tags:
      - { name: contao.hook, hook: generatePage }
  Alnv\ContaoGroundingPagesBundle\InsertTags\GlobalsInertTag:
    tags:
      - { name: contao.hook, hook: replaceInsertTags }
  Alnv\ContaoGroundingPagesBundle\EventListener\SitemapListener:
    autowire: true
    tags:
      - name: kernel.event_listener
        event: Contao\CoreBundle\Event\SitemapEvent
        method: __invoke